# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stylying_Example.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# APP Imports
import sys
import os
import platform
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                          QSize, QTime, QTimer, QUrl, Qt, QEvent)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                         QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PyQt5.QtWidgets import *

class MainWindow(QMainWindow):
    def __init__(self):
        super.__init__(self)
        # MainWindow.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius : 20px")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(50, 64, 70, 50)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.main_frame)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(19, 0, 9, 14)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.result_frame = QtWidgets.QFrame(self.frame_8)
        self.result_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.result_frame.setStyleSheet("background-color: transparent;")
        self.result_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_frame.setObjectName("result_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.result_frame)
        self.horizontalLayout_2.setContentsMargins(94, 20, 57, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.display_line = QtWidgets.QLineEdit(self.result_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_line.sizePolicy().hasHeightForWidth())
        self.display_line.setSizePolicy(sizePolicy)
        self.display_line.setMinimumSize(QtCore.QSize(0, 40))
        self.display_line.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(180, 180, 180);\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    font: bold 15px;\n"
"}")
        self.display_line.setText("")
        self.display_line.setReadOnly(True)
        self.display_line.setObjectName("display_line")
        self.horizontalLayout_2.addWidget(self.display_line)
        self.button_ok = QtWidgets.QPushButton(self.result_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ok.sizePolicy().hasHeightForWidth())
        self.button_ok.setSizePolicy(sizePolicy)
        self.button_ok.setMinimumSize(QtCore.QSize(50, 50))
        self.button_ok.setMaximumSize(QtCore.QSize(50, 70))
        self.button_ok.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    font: bold 15px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(180, 180, 180);\n"
"}")
        self.button_ok.setObjectName("button_ok")
        self.horizontalLayout_2.addWidget(self.button_ok)
        self.verticalLayout_3.addWidget(self.result_frame)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.keypad_frame = QtWidgets.QFrame(self.main_frame)
        self.keypad_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keypad_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keypad_frame.setObjectName("keypad_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.keypad_frame)
        self.verticalLayout_6.setContentsMargins(30, -1, 30, 10)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_123 = QtWidgets.QFrame(self.keypad_frame)
        self.frame_123.setStyleSheet("background-color: transparent;")
        self.frame_123.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_123.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_123.setObjectName("frame_123")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_123)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_1 = QtWidgets.QPushButton(self.frame_123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        self.button_1.setMinimumSize(QtCore.QSize(80, 80))
        self.button_1.setMaximumSize(QtCore.QSize(80, 80))
        self.button_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 40px;\n"
"    border-color: rgb(180, 180, 180);\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 85, 85);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.button_1.setObjectName("button_1")
        self.horizontalLayout_3.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.frame_123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_2.sizePolicy().hasHeightForWidth())
        self.button_2.setSizePolicy(sizePolicy)
        self.button_2.setMinimumSize(QtCore.QSize(80, 80))
        self.button_2.setMaximumSize(QtCore.QSize(80, 80))
        self.button_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 40px;\n"
"    border-color: rgb(180, 180, 180);\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 85, 85);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.button_2.setObjectName("button_2")
        self.horizontalLayout_3.addWidget(self.button_2)
        self.button_3 = QtWidgets.QPushButton(self.frame_123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_3.sizePolicy().hasHeightForWidth())
        self.button_3.setSizePolicy(sizePolicy)
        self.button_3.setMinimumSize(QtCore.QSize(80, 80))
        self.button_3.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 40px;\n"
"    border-color: rgb(180, 180, 180);\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 85, 85);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.button_3.setObjectName("button_3")
        self.horizontalLayout_3.addWidget(self.button_3)
        self.verticalLayout_6.addWidget(self.frame_123)
        self.verticalLayout_2.addWidget(self.keypad_frame)
        self.verticalLayout.addWidget(self.main_frame)
        self.title_bar = QtWidgets.QFrame(self.centralwidget)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(4, 160, 255, 255), stop:1 rgb(1, 212, 255));\n"
"border-color: none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.title_container_2 = QtWidgets.QFrame(self.title_bar)
        self.title_container_2.setStyleSheet("background:transparent")
        self.title_container_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_container_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_container_2.setObjectName("title_container_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.title_container_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.title_container_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(56, 56, 56);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_4.addWidget(self.title_container_2)
        self.top_right_btns = QtWidgets.QFrame(self.title_bar)
        self.top_right_btns.setMaximumSize(QtCore.QSize(200, 16777215))
        self.top_right_btns.setStyleSheet("background:transparent")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.restoreButton = QtWidgets.QPushButton(self.top_right_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restoreButton.sizePolicy().hasHeightForWidth())
        self.restoreButton.setSizePolicy(sizePolicy)
        self.restoreButton.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 105, 105);\n"
"    border-radius: 5px;\n"
"}")
        self.restoreButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Binary_clock_assets/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon)
        self.restoreButton.setIconSize(QtCore.QSize(32, 32))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_5.addWidget(self.restoreButton)
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeButton.sizePolicy().hasHeightForWidth())
        self.minimizeButton.setSizePolicy(sizePolicy)
        self.minimizeButton.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(170, 255, 127);\n"
"    border-radius: 5px;\n"
"}")
        self.minimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Binary_clock_assets/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon1)
        self.minimizeButton.setIconSize(QtCore.QSize(32, 32))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_5.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"    border-radius: 5px;\n"
"}")
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Binary_clock_assets/X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setIconSize(QtCore.QSize(32, 32))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        self.horizontalLayout_4.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton::!pressed\n"
"            {\n"
"                font: 75 10pt \"Microsoft YaHei UI\";\n"
"                font-weight: bold;\n"
"                color: rgb(255, 255, 255);\n"
"                border-style: solid;\n"
"                border-radius:21px;\n"
"                background:gray;\n"
"            }\n"
"            QPushButton::pressed\n"
"            {\n"
"                font: 75 10pt \"Microsoft YaHei UI\";\n"
"                font-weight: bold;\n"
"                color: rgb(255, 255, 255);\n"
"                border-style: solid;\n"
"                border-radius:21px;\n"
"                background-color : red;\n"
"            }")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalScrollBar.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 2px solid grey;\n"
"    background: #32CC99;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: white;\n"
"    min-width: 20px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 2px solid grey;\n"
"    background: #32CC99;\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid grey;\n"
"    background: #32CC99;\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: 2px solid grey;\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout.addWidget(self.horizontalScrollBar)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: red;\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    height: 10px;\n"
"    background: green;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: pink;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.button_ok.setText(_translate("MainWindow", "OK"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "Binary Clock"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
# import binary_clock_icons_rc


# Execute app
#
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()

    sys.exit(app.exec_())
else:
    print(__name__, "hh")
